os: linux
dist: xenial
language: python

notifications:
    email: false

jobs:
  include:
    - services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PLAT=manylinux2014_x86_64
           PY_MAJOR=3 PY_MINOR=5
    - services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PLAT=manylinux2014_x86_64
           PY_MAJOR=3 PY_MINOR=6
    - services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PLAT=manylinux2014_x86_64
           PY_MAJOR=3 PY_MINOR=8

env:
    global:
      - TWINE_USERNAME=__token__

install:
    - docker pull $DOCKER_IMAGE

script:
    - docker run --rm -e PLAT=$PLAT -e PY_MAJOR=$PY_MAJOR -e PY_MINOR=$PY_MINOR -v `pwd`:/io $DOCKER_IMAGE /io/.ci/.bld-whl.sh
    - ls wheelhouse

after_success:
    - |
      if [[ $TRAVIS_TAG ]]; then
        python3 -m pip install twine
        python3 -m twine upload --verbose wheelhouse/*.whl
      fi
