os: linux
dist: xenial
language: python

jobs:
  include:
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
           PLAT=manylinux2014_x86_64

install:
    - docker pull $DOCKER_IMAGE

script:
    - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/.ci/.bld-whl.sh
    - ls wheelhouse

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - bash .ci/.deploy.sh
